---
roles:
  rpmbuild:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 1024]
    provisioners:
      - type: hosts
      - type: shell
        inline: |
            yum -y install vim curl git rpm-build redhat-rpm-config java-1.7.0-openjdk-devel
            wget http://mirrors.ukfast.co.uk/sites/ftp.apache.org//ant/binaries/apache-ant-1.9.6-bin.tar.gz
            tar xzf apache-ant-1.9.6-bin.tar.gz
            mv apache-ant-1.9.6 /opt
            ln -s /opt/apache-ant-1.9.6 /opt/ant
            ln -s /opt/ant/bin/ant /usr/bin/ant
            echo 'ANT_HOME=/opt/ant' >> /etc/profile
            
            
            
            
            
            
            
            
            
